{% set name = "napari-macrokit" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-macrokit-{{ version }}.tar.gz
  sha256: 9f49f629f22d0088d482b7292415a76205723b4bbac82319cd5e0fd43022b507

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - macro-kit >=0.4.0
    - magicgui
    - numpy
    - napari
    - pandas
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - napari_macrokit
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hanjinliu/napari-macrokit
  summary: Executable script generation for napari plugins
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinliu
    - jaimergp
